spring:
  master:
    datasource:
      name: mysql
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://132.254.28.93:8921/${MYSQLNAME:ismartdb_alert}?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
      username: db_man
      password: Akk_220620
      initialSize: 10
      maxActive: 100
      minIdle: 10
      maxWait: 6000
  datasource:
    druid:
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 10
      maxIdle: 15
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      maxOpenPreparedStatements: 20
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      stat-view-servlet.enabled: false



